import { isoDaysAgo, lineSum, type CategoryId, type DrawerId, type LineItem, type PaymentId, type Receipt, type SlipStatus } from "@/lib/receipts/model";

type Seed = {
  id: string;
  merchant: string;
  place: string;
  daysAgo: number;
  category: CategoryId;
  payment: PaymentId;
  drawer: DrawerId;
  status: SlipStatus;
  confidence: number;
  notes: string;
  tax: number;
  tip: number;
  lineItems: LineItem[];
};

const SEEDS: Seed[] = [
  {
    id: "sample-tai-cheong",
    merchant: "Tai Cheong",
    place: "Lyndhurst Terrace, Central",
    daysAgo: 2,
    category: "dining",
    payment: "octopus",
    drawer: "personal",
    status: "filed",
    confidence: 0.94,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "Egg tart", qty: 2, amount: 24 },
      { name: "Milk tea", qty: 1, amount: 22 },
      { name: "Pineapple bun", qty: 2, amount: 40 },
    ],
  },
  {
    id: "sample-wellcome",
    merchant: "Wellcome",
    place: "Queen's Road, Sheung Wan",
    daysAgo: 4,
    category: "groceries",
    payment: "octopus",
    drawer: "personal",
    status: "filed",
    confidence: 0.91,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "Milk 1L", qty: 1, amount: 22.9 },
      { name: "Jasmine rice", qty: 1, amount: 78 },
      { name: "Eggs 12", qty: 1, amount: 28.5 },
      { name: "Broccoli", qty: 1, amount: 16 },
      { name: "Soy sauce", qty: 1, amount: 18 },
      { name: "Yogurt", qty: 1, amount: 36 },
      { name: "Bread", qty: 1, amount: 22 },
      { name: "Apples", qty: 1, amount: 31 },
      { name: "Detergent", qty: 1, amount: 60 },
    ],
  },
  {
    id: "sample-pacific",
    merchant: "Pacific Coffee",
    place: "ifc mall",
    daysAgo: 1,
    category: "dining",
    payment: "card",
    drawer: "work",
    status: "review",
    confidence: 0.62,
    notes: "Card slip was faint. Check the total before filing.",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "Flat white", qty: 1, amount: 38 },
      { name: "Banana bread", qty: 1, amount: 16 },
    ],
  },
  {
    id: "sample-taxi",
    merchant: "Urban Taxi",
    place: "Central to Kennedy Town",
    daysAgo: 6,
    category: "transit",
    payment: "octopus",
    drawer: "work",
    status: "filed",
    confidence: 0.88,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [{ name: "Metered fare", qty: 1, amount: 78 }],
  },
  {
    id: "sample-harbour",
    merchant: "Harbour Grand",
    place: "North Point",
    daysAgo: 11,
    category: "travel",
    payment: "card",
    drawer: "trip",
    status: "filed",
    confidence: 0.9,
    notes: "One night, client offsite.",
    tax: 0,
    tip: 170,
    lineItems: [
      { name: "Harbour room", qty: 1, amount: 1580 },
      { name: "Breakfast", qty: 1, amount: 110 },
    ],
  },
  {
    id: "sample-mannings",
    merchant: "Mannings",
    place: "Admiralty",
    daysAgo: 8,
    category: "health",
    payment: "fps",
    drawer: "personal",
    status: "filed",
    confidence: 0.93,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "Vitamin C", qty: 1, amount: 89.9 },
      { name: "Plasters", qty: 1, amount: 40 },
    ],
  },
  {
    id: "sample-fortress",
    merchant: "Fortress",
    place: "Causeway Bay",
    daysAgo: 18,
    category: "shopping",
    payment: "card",
    drawer: "personal",
    status: "filed",
    confidence: 0.96,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [{ name: "Wireless earbuds", qty: 1, amount: 2480 }],
  },
  {
    id: "sample-ink",
    merchant: "Ink & Co.",
    place: "Wan Chai",
    daysAgo: 15,
    category: "office",
    payment: "fps",
    drawer: "work",
    status: "filed",
    confidence: 0.9,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "A4 paper", qty: 5, amount: 140 },
      { name: "Notebooks", qty: 2, amount: 46 },
      { name: "Pens", qty: 1, amount: 30 },
    ],
  },
  {
    id: "sample-orchid",
    merchant: "Golden Orchid",
    place: "Soho",
    daysAgo: 34,
    category: "dining",
    payment: "card",
    drawer: "work",
    status: "filed",
    confidence: 0.92,
    notes: "Team dinner. Only the goose is yours.",
    tax: 0,
    tip: 60,
    lineItems: [
      { name: "Roast goose", qty: 1, amount: 480, mine: true },
      { name: "Greens", qty: 1, amount: 88, mine: false },
      { name: "Rice", qty: 2, amount: 40, mine: false },
    ],
  },
  {
    id: "sample-mart",
    merchant: "Daily Mart",
    place: "Sai Ying Pun",
    daysAgo: 40,
    category: "groceries",
    payment: "octopus",
    drawer: "personal",
    status: "filed",
    confidence: 0.87,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [
      { name: "Fruit", qty: 1, amount: 46.2 },
      { name: "Noodles", qty: 2, amount: 32 },
      { name: "Tofu", qty: 1, amount: 18 },
      { name: "Tea", qty: 1, amount: 42 },
      { name: "Snacks", qty: 1, amount: 50 },
    ],
  },
  {
    id: "sample-ael",
    merchant: "Airport Express",
    place: "Hong Kong to Airport",
    daysAgo: 28,
    category: "transit",
    payment: "octopus",
    drawer: "trip",
    status: "filed",
    confidence: 0.95,
    notes: "",
    tax: 0,
    tip: 0,
    lineItems: [{ name: "Single journey", qty: 1, amount: 115 }],
  },
  {
    id: "sample-clp",
    merchant: "CLP Power",
    place: "Home account",
    daysAgo: 45,
    category: "utilities",
    payment: "fps",
    drawer: "tax",
    status: "filed",
    confidence: 0.9,
    notes: "Electricity, previous cycle.",
    tax: 0,
    tip: 0,
    lineItems: [{ name: "Electricity charges", qty: 1, amount: 486.3 }],
  },
];

export function buildSamples(): Receipt[] {
  const now = Date.now();
  return SEEDS.map((seed) => {
    const subtotal = lineSum(seed.lineItems);
    const total = Math.round((subtotal + seed.tax + seed.tip) * 100) / 100;
    const date = isoDaysAgo(seed.daysAgo);
    return {
      id: seed.id,
      image: null,
      merchant: seed.merchant,
      place: seed.place,
      date,
      currency: "HKD",
      subtotal,
      tax: seed.tax,
      tip: seed.tip,
      total,
      category: seed.category,
      payment: seed.payment,
      drawer: seed.drawer,
      notes: seed.notes,
      lineItems: seed.lineItems,
      status: seed.status,
      confidence: seed.confidence,
      origin: "sample" as const,
      createdAt: now - seed.daysAgo * 86_400_000,
    };
  });
}
